name: Build and Deploy to Main Branch

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Workflow Triggered
        run: echo "Workflow has been triggered by a push to develop."

      - name: Checkout develop branch
        uses: actions/checkout@v3
        with:
          # We need to check out the 'develop' branch to get the source code.
          ref: develop

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install and Build
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        run: |
          npm ci
          npm run build
          node scripts/build_package.mjs

      - name: List files for debugging
        run: ls -R

      - name: List dist contents
        run: ls -R dist | head -20

      - name: Deploy to main branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: main
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: "Deploy: ${{ github.event.head_commit.message }}"

      - name: Workflow Completed
        run: echo "Workflow has completed successfully."
